name: Run on workflow_run

on:
  workflow_run:
    workflows:
      - "Request"
    types:
      - completed

jobs:
  process-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Download environment data
      id: download
      uses: envoyproxy/toolshed/gh-actions/github/artifact/download@actions-v0.3.16
      with:
        name: hello-artifact
        path: .
        run-id: ${{ github.event.workflow_run.id }}
    - name: Print contents of hello.txt
      run: cat hello.txt