name: Request

on:
  pull_request_target:

jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Create hello.txt
      run: echo "Trusted content" > hello.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-artifact
        path: hello.txt